### PR TITLE
Correction of typo in nginx.conf

### PR DESCRIPTION
**Pull request by polytan02**

### CODE REVIEW

**Comment by mrtino** [comment]
Thanks !

**Comment by mrtino** [comment]
Done.
I don't have time anymore to work on MyCryptoChat. And it seems that the project has been stopped.

**Comment by opi** [comment]
You're right, last project activity was during september 2014 (https://github.com/HowTommy/mycryptochat).
I'll make a pull request to the project readme to indicate that the upstream project is stopped, and YunoHost integration is not maintained anymore.

**Comment by opi** [comment]
If you're ok with https://github.com/mrtino/mycryptochat_ynh/pull/7 you can do the merge. Thanks for your work.

**Pull request merged**
